spring:
  application:
    name: ShieldMe-Authentication-Service

# --- Database Configurations ---
  data:
    mongodb:
#      uri: mongodb://localhost:27017/ShieldMe  # MongoDB URI
      uri: mongodb+srv://ajaynegi3345:m7CdBtFBJz4xFVcT@mongocluster.epkox.mongodb.net/?retryWrites=true&w=majority&appName=MongoCluster
      database: ShieldMe
      auto-index-creation: true



# --- Server Error Configurations ---
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
    include-exception: true
  port: 8080  # Server port configuration