spring:
  application:
    name: Positive-Affirmations-Service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ShieldMe
      database: ShieldMe
      auto-index-creation: true
server:
  port: 8083

logging:
  level:
    org:
      springframework:
        data:
          mongodb=DEBUG: